# Generated by Django 4.0.2 on 2022-11-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_library_bookinstance_owner_library'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='library',
            options={'ordering': ['name'], 'verbose_name': 'Library', 'verbose_name_plural': 'Libraries'},
        ),
    ]
