# Generated by Django 4.0.2 on 2022-11-14 15:57

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_alter_library_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='library',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='library',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
